Scrape Started!
		WEBSITE | https://snakehustle.netlify.app |

Downloading Resource | https://snakehustle.netlify.app/downloads/Logo.ico |

Download Complete | https://snakehustle.netlify.app/downloads/Logo.ico |

Downloading Webpage | https://snakehustle.netlify.app/assets/index-6X3Up7uB.css |

Downloading Webpage | https://snakehustle.netlify.app/assets/index-D3wMHnLP.js |

Download Failed | http://www.w3.org/1999/xhtml |


Error: Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\website.py", line 311, in check_and_call
    content = BeautifulSoup(content, features="xml").prettify()
              ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\new\Lib\site-packages\bs4\__init__.py", line 364, in __init__
    raise FeatureNotFound(
    ...<3 lines>...
    )
bs4.exceptions.FeatureNotFound: Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?


Download Failed | https://reactjs.org/docs/error-decoder.html?invariant= |


Error: Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\webpage.py", line 19, in download_resource_safe
    with urllib.request.urlopen(url) as response:
         ~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 495, in open
    response = meth(req, response)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 604, in http_response
    response = self.parent.error(
        'http', request, response, code, msg, hdrs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 527, in error
    result = self._call_chain(*args)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 720, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 495, in open
    response = meth(req, response)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 604, in http_response
    response = self.parent.error(
        'http', request, response, code, msg, hdrs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 533, in error
    return self._call_chain(*args)
           ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 613, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\website.py", line 274, in check_and_call
    content = download_resource_safe(url_requested)
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\webpage.py", line 41, in download_resource_safe
    raise exceptions.FileDownloadError(url)
exceptions.FileDownloadError: Couldn't download file !

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\website.py", line 280, in check_and_call
    raise exceptions.FileDownloadError(url)
exceptions.FileDownloadError: Couldn't download file !


Download Failed | /$ |


Error: Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\webpage.py", line 19, in download_resource_safe
    with urllib.request.urlopen(url) as response:
         ~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 495, in open
    response = meth(req, response)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 604, in http_response
    response = self.parent.error(
        'http', request, response, code, msg, hdrs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 533, in error
    return self._call_chain(*args)
           ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 613, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\website.py", line 274, in check_and_call
    content = download_resource_safe(url_requested)
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\webpage.py", line 41, in download_resource_safe
    raise exceptions.FileDownloadError(url)
exceptions.FileDownloadError: Couldn't download file !

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\website.py", line 280, in check_and_call
    raise exceptions.FileDownloadError(url)
exceptions.FileDownloadError: Couldn't download file !


Download Failed | Snake Game.exe |


Error: Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\webpage.py", line 19, in download_resource_safe
    with urllib.request.urlopen(url) as response:
         ~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 489, in open
    response = self._open(req, data)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 506, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
                              '_open', req)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 1367, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        context=self._context)
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 1288, in do_open
    h = http_class(host, timeout=req.timeout, **http_conn_args)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\http\client.py", line 1462, in __init__
    super(HTTPSConnection, self).__init__(host, port, timeout,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
                                          source_address,
                                          ^^^^^^^^^^^^^^^
                                          blocksize=blocksize)
                                          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\http\client.py", line 884, in __init__
    self._validate_host(self.host)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\http\client.py", line 1291, in _validate_host
    raise InvalidURL(f"URL can't contain control characters. {host!r} "
                     f"(found at least {match.group()!r})")
http.client.InvalidURL: URL can't contain control characters. 'Snake Game.exe' (found at least ' ')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\website.py", line 274, in check_and_call
    content = download_resource_safe(url_requested)
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\webpage.py", line 41, in download_resource_safe
    raise exceptions.FileDownloadError(url)
exceptions.FileDownloadError: Couldn't download file !

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\website.py", line 280, in check_and_call
    raise exceptions.FileDownloadError(url)
exceptions.FileDownloadError: Couldn't download file !


Download Failed | /$ |


Error: Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\webpage.py", line 19, in download_resource_safe
    with urllib.request.urlopen(url) as response:
         ~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 495, in open
    response = meth(req, response)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 604, in http_response
    response = self.parent.error(
        'http', request, response, code, msg, hdrs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 533, in error
    return self._call_chain(*args)
           ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 613, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\website.py", line 274, in check_and_call
    content = download_resource_safe(url_requested)
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\webpage.py", line 41, in download_resource_safe
    raise exceptions.FileDownloadError(url)
exceptions.FileDownloadError: Couldn't download file !

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\website.py", line 280, in check_and_call
    raise exceptions.FileDownloadError(url)
exceptions.FileDownloadError: Couldn't download file !


Download Failed | /$ |


Error: Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\webpage.py", line 19, in download_resource_safe
    with urllib.request.urlopen(url) as response:
         ~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 495, in open
    response = meth(req, response)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 604, in http_response
    response = self.parent.error(
        'http', request, response, code, msg, hdrs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 533, in error
    return self._call_chain(*args)
           ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 613, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\website.py", line 274, in check_and_call
    content = download_resource_safe(url_requested)
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\webpage.py", line 41, in download_resource_safe
    raise exceptions.FileDownloadError(url)
exceptions.FileDownloadError: Couldn't download file !

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\website.py", line 280, in check_and_call
    raise exceptions.FileDownloadError(url)
exceptions.FileDownloadError: Couldn't download file !


Download Failed | /$ |


Error: Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\webpage.py", line 19, in download_resource_safe
    with urllib.request.urlopen(url) as response:
         ~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 495, in open
    response = meth(req, response)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 604, in http_response
    response = self.parent.error(
        'http', request, response, code, msg, hdrs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 533, in error
    return self._call_chain(*args)
           ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 613, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\website.py", line 274, in check_and_call
    content = download_resource_safe(url_requested)
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\webpage.py", line 41, in download_resource_safe
    raise exceptions.FileDownloadError(url)
exceptions.FileDownloadError: Couldn't download file !

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\website.py", line 280, in check_and_call
    raise exceptions.FileDownloadError(url)
exceptions.FileDownloadError: Couldn't download file !


Download Failed | Snake Game.exe |


Error: Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\webpage.py", line 19, in download_resource_safe
    with urllib.request.urlopen(url) as response:
         ~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 489, in open
    response = self._open(req, data)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 506, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
                              '_open', req)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 1367, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        context=self._context)
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 1288, in do_open
    h = http_class(host, timeout=req.timeout, **http_conn_args)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\http\client.py", line 1462, in __init__
    super(HTTPSConnection, self).__init__(host, port, timeout,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
                                          source_address,
                                          ^^^^^^^^^^^^^^^
                                          blocksize=blocksize)
                                          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\http\client.py", line 884, in __init__
    self._validate_host(self.host)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\http\client.py", line 1291, in _validate_host
    raise InvalidURL(f"URL can't contain control characters. {host!r} "
                     f"(found at least {match.group()!r})")
http.client.InvalidURL: URL can't contain control characters. 'Snake Game.exe' (found at least ' ')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\website.py", line 274, in check_and_call
    content = download_resource_safe(url_requested)
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\webpage.py", line 41, in download_resource_safe
    raise exceptions.FileDownloadError(url)
exceptions.FileDownloadError: Couldn't download file !

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\website.py", line 280, in check_and_call
    raise exceptions.FileDownloadError(url)
exceptions.FileDownloadError: Couldn't download file !


Download Failed | /downloads/profile.png |


Error: Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\webpage.py", line 19, in download_resource_safe
    with urllib.request.urlopen(url) as response:
         ~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 189, in urlopen
    return opener.open(url, data, timeout)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 495, in open
    response = meth(req, response)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 604, in http_response
    response = self.parent.error(
        'http', request, response, code, msg, hdrs)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 533, in error
    return self._call_chain(*args)
           ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\urllib\request.py", line 613, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\website.py", line 274, in check_and_call
    content = download_resource_safe(url_requested)
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\webpage.py", line 41, in download_resource_safe
    raise exceptions.FileDownloadError(url)
exceptions.FileDownloadError: Couldn't download file !

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\website.py", line 280, in check_and_call
    raise exceptions.FileDownloadError(url)
exceptions.FileDownloadError: Couldn't download file !


Download Failed | http://www.w3.org/1999/xhtml |


Error: Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\website.py", line 311, in check_and_call
    content = BeautifulSoup(content, features="xml").prettify()
              ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\new\Lib\site-packages\bs4\__init__.py", line 364, in __init__
    raise FeatureNotFound(
    ...<3 lines>...
    )
bs4.exceptions.FeatureNotFound: Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?


Download Failed | http://www.w3.org/1999/xhtml |


Error: Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\website.py", line 311, in check_and_call
    content = BeautifulSoup(content, features="xml").prettify()
              ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\new\Lib\site-packages\bs4\__init__.py", line 364, in __init__
    raise FeatureNotFound(
    ...<3 lines>...
    )
bs4.exceptions.FeatureNotFound: Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?


Download Failed | http://www.w3.org/1999/xhtml |


Error: Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\website.py", line 311, in check_and_call
    content = BeautifulSoup(content, features="xml").prettify()
              ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\new\Lib\site-packages\bs4\__init__.py", line 364, in __init__
    raise FeatureNotFound(
    ...<3 lines>...
    )
bs4.exceptions.FeatureNotFound: Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?


Download Failed | http://www.w3.org/XML/1998/namespace |


Error: Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\website.py", line 311, in check_and_call
    content = BeautifulSoup(content, features="xml").prettify()
              ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\new\Lib\site-packages\bs4\__init__.py", line 364, in __init__
    raise FeatureNotFound(
    ...<3 lines>...
    )
bs4.exceptions.FeatureNotFound: Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?


Downloading Resource | https://snakehustle.netlify.app/downloads/picture_main.png |

Download Complete | https://snakehustle.netlify.app/downloads/picture_main.png |

Download Failed | http://www.w3.org/1999/xhtml |


Error: Traceback (most recent call last):
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\website.py", line 311, in check_and_call
    content = BeautifulSoup(content, features="xml").prettify()
              ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\OneDrive\Desktop\Webber\new\Lib\site-packages\bs4\__init__.py", line 364, in __init__
    raise FeatureNotFound(
    ...<3 lines>...
    )
bs4.exceptions.FeatureNotFound: Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?


Downloading Resource | https://github.com/YogyaChugh/SnakeGame/releases/download/v1.0.0/Snake_Game_Windows.exe |

Download Complete | https://github.com/YogyaChugh/SnakeGame/releases/download/v1.0.0/Snake_Game_Windows.exe |

Downloading Resource | https://github.com/YogyaChugh/SnakeGame/releases/download/v1.0.0/Snake_Hustler_Linux |

Download Complete | https://github.com/YogyaChugh/SnakeGame/releases/download/v1.0.0/Snake_Hustler_Linux |
				================================
				SUCCESS SCRAPING WEBSITE https://snakehustle.netlify.app
				================================
Logger for https://snakehustle.netlify.app closed !